version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    

  mysql_inventory:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_inventory_data:/var/lib/mysql

  mysql_order:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_order_data:/var/lib/mysql



  mysql_product:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_product_data:/var/lib/mysql

  service-discovery:
    image: yasminehaidri/service-discovery:latest
    ports:
      - "8761:8761"
    

  product-service:
    image: yasminehaidri/product-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery
      - mysql_product
      - rabbitmq

  order-service:
    image: yasminehaidri/order-service:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql_order
      - service-discovery
      - rabbitmq


  inventory-service:
    image: yasminehaidri/inventory-service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery
      - mysql_inventory
      - rabbitmq

  api-gateway:
    image: yasminehaidri/api-gateway:latest
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - service-discovery

