version: '4'

services:
  service-discovery:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge